### ISSUE TITLE
Awesome Font Framework

### ISSUE THREAD

**Issue by pdp2015** [Hendrik44/pi-weather-app#3]
Just had a look at this project and xcode cant seem to find Font.Awesome Framework?

How do I get that to test the app as would like to see how its put together

Many Thanks

**Comment by Hendrik44** [comment]
I have to test it and will give you feedback soon.

**Comment by Hendrik44** [comment]
Do you installed all framesworks via Carthage? I don't have any issue. The app runs fine.

**Comment by Hendrik44** [comment]
No response for two weeks. Close
